#!/usr/bin/env bash
# Install Pre-Commit Hook for Constitutional Compliance
# Purpose: Install git pre-commit hook to enforce constitutional compliance
# JIRA: INFRA-472
# Usage: ./scripts/compliance/install-pre-commit-hook.sh

set -euo pipefail

# Colors
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
NC='\033[0m'

HOOK_PATH=".git/hooks/pre-commit"
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_ROOT="$(cd "${SCRIPT_DIR}/../.." && pwd)"

echo "Installing Constitutional Compliance Pre-Commit Hook..."

# Check if git repo
if [[ ! -d ".git" ]]; then
    echo "Error: Not a git repository"
    exit 1
fi

# Create hooks directory if needed
mkdir -p ".git/hooks"

# Create pre-commit hook
cat > "${HOOK_PATH}" << 'EOF'
#!/usr/bin/env bash
# Pre-Commit Hook: Constitutional Compliance Check
# Auto-generated by scripts/compliance/install-pre-commit-hook.sh

set -euo pipefail

echo "Running constitutional compliance check..."

# Run the constitutional self-check script
if [[ -f "scripts/compliance/constitutional-self-check.sh" ]]; then
    if bash scripts/compliance/constitutional-self-check.sh; then
        echo "✓ Constitutional compliance check passed"
        exit 0
    else
        echo ""
        echo "✗ Constitutional compliance check failed"
        echo "  Please address the errors above before committing"
        echo "  Run: ./scripts/compliance/constitutional-self-check.sh --fix"
        echo ""
        echo "To bypass (NOT RECOMMENDED): git commit --no-verify"
        exit 1
    fi
else
    echo "⚠ Warning: Constitutional compliance script not found"
    echo "  Expected: scripts/compliance/constitutional-self-check.sh"
    echo "  Allowing commit to proceed..."
    exit 0
fi
EOF

# Make hook executable
chmod +x "${HOOK_PATH}"

echo -e "${GREEN}✓ Pre-commit hook installed successfully${NC}"
echo ""
echo "The hook will run on every commit to validate:"
echo "  - Article I: JIRA-first approach"
echo "  - Article II: Context management"
echo "  - Article VIIa: No hardcoded IPs (IaC mandate)"
echo "  - Article X: Accurate status reporting"
echo "  - Article XIII: Proactive compliance"
echo ""
echo "To test the hook, run:"
echo "  ./scripts/compliance/constitutional-self-check.sh"
echo ""
echo -e "${YELLOW}Note: Hook can be bypassed with 'git commit --no-verify' (not recommended)${NC}"
