#!/bin/bash
echo "🧪 PAWS360 Quick Test Commands"
echo "=============================="
echo ""
echo "🚀 BEFORE PUSHING CHANGES:"
echo "  ./test-e2e-local.sh                    # Full E2E test (mirrors CI)"
echo ""
echo "⚡ QUICK CHECKS:"
echo "  make -f Makefile.dev auth-test         # Test authentication only"
echo "  make -f Makefile.dev db-status         # Check database & accounts"
echo "  make -f Makefile.dev logs              # View application logs"
echo ""
echo "🔧 DEVELOPMENT:"
echo "  make -f Makefile.dev build             # Build backend JAR"
echo "  make -f Makefile.dev dev               # Start dev environment"
echo "  make -f Makefile.dev clean             # Clean up everything"
echo ""
echo "📚 HELP:"
echo "  make -f Makefile.dev help              # Show all commands"
echo "  cat LOCAL_TESTING.md                   # Full testing guide"
echo ""
echo "🎯 REMEMBER: Test locally = No CI shame!"