#!/bin/bash

# PAWS360 Database Setup Script
# This script automates the database setup process

set -e  # Exit on any error

# Colors for output
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
NC='\033[0m' # No Color

# Configuration
DB_NAME="paws360"
DB_USER="paws360_admin"
DB_HOST="localhost"
DB_PORT="5432"

echo -e "${BLUE}🐘 PAWS360 Database Setup${NC}"
echo "================================="

# Check if PostgreSQL is installed
if ! command -v psql &> /dev/null; then
    echo -e "${RED}❌ PostgreSQL is not installed. Please install PostgreSQL first.${NC}"
    echo "   Ubuntu/Debian: sudo apt install postgresql postgresql-contrib"
    echo "   macOS: brew install postgresql"
    echo "   CentOS/RHEL: sudo yum install postgresql-server postgresql-contrib"
    exit 1
fi

# Check if PostgreSQL is running
if ! sudo -u postgres psql -c "SELECT 1;" &> /dev/null; then
    echo -e "${RED}❌ PostgreSQL is not running. Please start PostgreSQL service.${NC}"
    echo "   Ubuntu/Debian: sudo systemctl start postgresql"
    echo "   macOS: brew services start postgresql"
    echo "   CentOS/RHEL: sudo systemctl start postgresql"
    exit 1
fi

echo -e "${GREEN}✅ PostgreSQL is running${NC}"

# Get database password
echo -e "${YELLOW}Enter password for database user '${DB_USER}':${NC}"
read -s DB_PASSWORD

if [ -z "$DB_PASSWORD" ]; then
    echo -e "${RED}❌ Password cannot be empty${NC}"
    exit 1
fi

echo -e "\n${BLUE}Setting up database...${NC}"

# Create user and database
sudo -u postgres psql << EOF
-- Create user if not exists
DO \$\$
BEGIN
   IF NOT EXISTS (SELECT FROM pg_catalog.pg_roles WHERE rolname = '${DB_USER}') THEN
      CREATE USER ${DB_USER} WITH PASSWORD '${DB_PASSWORD}';
   END IF;
END
\$\$;

-- Create database if not exists
SELECT 'CREATE DATABASE ${DB_NAME} OWNER ${DB_USER}'
WHERE NOT EXISTS (SELECT FROM pg_database WHERE datname = '${DB_NAME}')\gexec

-- Grant privileges
GRANT ALL PRIVILEGES ON DATABASE ${DB_NAME} TO ${DB_USER};
EOF

echo -e "${GREEN}✅ Database and user created${NC}"

# Test connection
echo -e "${BLUE}Testing database connection...${NC}"
export PGPASSWORD="${DB_PASSWORD}"

if psql -h "${DB_HOST}" -p "${DB_PORT}" -U "${DB_USER}" -d "${DB_NAME}" -c "SELECT version();" &> /dev/null; then
    echo -e "${GREEN}✅ Database connection successful${NC}"
else
    echo -e "${RED}❌ Database connection failed${NC}"
    exit 1
fi

# Check for DDL file
DDL_FILE="paws360_database_ddl.sql"
if [ ! -f "$DDL_FILE" ]; then
    echo -e "${RED}❌ DDL file '${DDL_FILE}' not found in current directory${NC}"
    echo "   Please ensure you're running this script from the database directory"
    exit 1
fi

# Run DDL
echo -e "${BLUE}Creating database schema...${NC}"
psql -h "${DB_HOST}" -p "${DB_PORT}" -U "${DB_USER}" -d "${DB_NAME}" -f "$DDL_FILE"

echo -e "${GREEN}✅ Database schema created${NC}"

# Check for seed data
SEED_FILE="paws360_seed_data.sql"
if [ -f "$SEED_FILE" ]; then
    echo -e "${YELLOW}Seed data file found. Load sample data? (y/n):${NC}"
    read -r LOAD_SEED

    if [[ $LOAD_SEED =~ ^[Yy]$ ]]; then
        echo -e "${BLUE}Loading sample data (this may take a few minutes)...${NC}"
        psql -h "${DB_HOST}" -p "${DB_PORT}" -U "${DB_USER}" -d "${DB_NAME}" -f "$SEED_FILE"
        echo -e "${GREEN}✅ Sample data loaded${NC}"
    else
        echo -e "${YELLOW}Skipping sample data load${NC}"
    fi
else
    echo -e "${YELLOW}No seed data file found, skipping sample data load${NC}"
fi

# Run basic health check
echo -e "${BLUE}Running health check...${NC}"

TABLE_COUNT=$(psql -h "${DB_HOST}" -p "${DB_PORT}" -U "${DB_USER}" -d "${DB_NAME}" -t -c "SELECT COUNT(*) FROM information_schema.tables WHERE table_schema = 'paws360';")

if [ "$TABLE_COUNT" -gt 0 ]; then
    echo -e "${GREEN}✅ Health check passed - $TABLE_COUNT tables created${NC}"
else
    echo -e "${RED}❌ Health check failed - no tables found${NC}"
    exit 1
fi

# Create .env file for application
ENV_FILE="../../.env.database"
cat > "$ENV_FILE" << EOF
# PAWS360 Database Configuration
# Generated by setup script on $(date)

DB_HOST=${DB_HOST}
DB_PORT=${DB_PORT}
DB_NAME=${DB_NAME}
DB_USER=${DB_USER}
DB_PASSWORD=${DB_PASSWORD}
DB_SCHEMA=paws360
DB_SSL=false
DB_MAX_CONNECTIONS=20

# Connection URL
DATABASE_URL=postgresql://${DB_USER}:${DB_PASSWORD}@${DB_HOST}:${DB_PORT}/${DB_NAME}?schema=paws360
EOF

echo -e "${GREEN}✅ Configuration saved to ${ENV_FILE}${NC}"

echo ""
echo -e "${GREEN}🎉 Database setup complete!${NC}"
echo ""
echo -e "${BLUE}Database Details:${NC}"
echo "  Host: ${DB_HOST}:${DB_PORT}"
echo "  Database: ${DB_NAME}"
echo "  User: ${DB_USER}"
echo "  Tables: ${TABLE_COUNT}"
echo ""
echo -e "${BLUE}Next Steps:${NC}"
echo "  1. Configure your application to use the database"
echo "  2. Import the Postman collection for API testing"
echo "  3. Start the PAWS360 application"
echo ""
echo -e "${YELLOW}Default Admin Credentials:${NC}"
echo "  Username: admin"
echo "  Email: admin@paws360.uwm.edu"
echo "  Password: admin123"
echo ""
echo -e "${BLUE}Useful Commands:${NC}"
echo "  Connect: psql -h ${DB_HOST} -p ${DB_PORT} -U ${DB_USER} -d ${DB_NAME}"
echo "  Backup: pg_dump -h ${DB_HOST} -p ${DB_PORT} -U ${DB_USER} -d ${DB_NAME} > backup.sql"
echo "  Monitor: psql -h ${DB_HOST} -p ${DB_PORT} -U ${DB_USER} -d ${DB_NAME} -c 'SELECT * FROM paws360.dashboard_metrics;'"