#!/bin/bash

# PAWS360 Database Setup Script
# This script automates the database setup process

set -e  # Exit on any error

# Colors for output
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
NC='\033[0m' # No Color

# Configuration - Using Docker container from setup script
DB_NAME="paws360_dev"
DB_USER="paws360"
DB_PASSWORD="paws360_dev_password"
DB_HOST="localhost"
DB_PORT="5432"
CONTAINER_NAME="paws360-postgres"

echo -e "${BLUE}🐘 PAWS360 Database Setup${NC}"
echo "================================="

# Check if Docker container is running
if ! docker ps | grep -q "$CONTAINER_NAME"; then
    echo -e "${RED}❌ PostgreSQL container '$CONTAINER_NAME' is not running.${NC}"
    echo "   Please run: bash scripts/setup/setup-from-scratch.sh"
    exit 1
fi

echo -e "${GREEN}✅ PostgreSQL container is running${NC}"

# Wait for PostgreSQL to be fully ready
echo -e "${BLUE}Waiting for database to be ready...${NC}"
max_attempts=30
attempt=0
while ! docker exec $CONTAINER_NAME pg_isready -U $DB_USER -d $DB_NAME >/dev/null 2>&1; do
    attempt=$((attempt + 1))
    if [ $attempt -eq $max_attempts ]; then
        echo -e "${RED}❌ Database connection failed after ${max_attempts} seconds${NC}"
        exit 1
    fi
    sleep 1
done

echo -e "${GREEN}✅ Database connection successful${NC}"

# Check for DDL file (look in database directory)
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
DDL_FILE="$SCRIPT_DIR/paws360_database_ddl.sql"
if [ ! -f "$DDL_FILE" ]; then
    echo -e "${RED}❌ DDL file '${DDL_FILE}' not found${NC}"
    echo "   Expected location: database/paws360_database_ddl.sql"
    exit 1
fi

# Run DDL
echo -e "${BLUE}Creating database schema...${NC}"
if ! cat "$DDL_FILE" | docker exec -i $CONTAINER_NAME psql -U $DB_USER -d $DB_NAME 2>&1 | tee /tmp/paws360_ddl.log | grep -i "ERROR" | head -5; then
    echo -e "${GREEN}✓${NC} No critical errors in schema creation"
else
    echo -e "${RED}✗${NC} Errors detected in DDL execution (see /tmp/paws360_ddl.log for details)"
    echo ""
    echo "First few errors:"
    grep -i "ERROR" /tmp/paws360_ddl.log | head -10
    exit 1
fi

# Verify schemas were created
echo -e "${BLUE}Verifying schemas...${NC}"
SCHEMA_COUNT=$(docker exec $CONTAINER_NAME psql -U $DB_USER -d $DB_NAME -t -c "SELECT COUNT(*) FROM information_schema.schemata WHERE schema_name IN ('paws360', 'audit');")
if [ "$SCHEMA_COUNT" -eq 2 ]; then
    echo -e "${GREEN}✓${NC} Schemas created successfully"
else
    echo -e "${RED}✗${NC} Schema creation failed (found $SCHEMA_COUNT/2 schemas)"
    exit 1
fi

echo -e "${GREEN}✅ Database schema created${NC}"

# Check for seed data
SEED_FILE="$SCRIPT_DIR/paws360_seed_data.sql"
if [ -f "$SEED_FILE" ]; then
    echo -e "${BLUE}Loading sample data (this may take a few minutes)...${NC}"
    cat "$SEED_FILE" | docker exec -i $CONTAINER_NAME psql -U $DB_USER -d $DB_NAME
    echo -e "${GREEN}✅ Sample data loaded${NC}"
else
    echo -e "${YELLOW}No seed data file found, skipping sample data load${NC}"
fi

# Run basic health check
echo -e "${BLUE}Running health check...${NC}"

TABLE_COUNT=$(docker exec $CONTAINER_NAME psql -U $DB_USER -d $DB_NAME -t -c "SELECT COUNT(*) FROM information_schema.tables WHERE table_schema = 'paws360';")

if [ "$TABLE_COUNT" -gt 0 ]; then
    echo -e "${GREEN}✅ Health check passed - $TABLE_COUNT tables created${NC}"
else
    echo -e "${RED}❌ Health check failed - no tables found${NC}"
    exit 1
fi

# Create .env file for application
ENV_FILE="../../.env.database"
cat > "$ENV_FILE" << EOF
# PAWS360 Database Configuration
# Generated by setup script on $(date)

DB_HOST=${DB_HOST}
DB_PORT=${DB_PORT}
DB_NAME=${DB_NAME}
DB_USER=${DB_USER}
DB_PASSWORD=${DB_PASSWORD}
DB_SCHEMA=paws360
DB_SSL=false
DB_MAX_CONNECTIONS=20

# Connection URL
DATABASE_URL=postgresql://${DB_USER}:${DB_PASSWORD}@${DB_HOST}:${DB_PORT}/${DB_NAME}?schema=paws360
EOF

echo -e "${GREEN}✅ Configuration saved to ${ENV_FILE}${NC}"

echo ""
echo -e "${GREEN}🎉 Database setup complete!${NC}"
echo ""
echo -e "${BLUE}Database Details:${NC}"
echo "  Host: ${DB_HOST}:${DB_PORT}"
echo "  Database: ${DB_NAME}"
echo "  User: ${DB_USER}"
echo "  Tables: ${TABLE_COUNT}"
echo ""
echo -e "${BLUE}Next Steps:${NC}"
echo "  1. Configure your application to use the database"
echo "  2. Import the Postman collection for API testing"
echo "  3. Start the PAWS360 application"
echo ""
echo -e "${YELLOW}Default Admin Credentials:${NC}"
echo "  Username: admin"
echo "  Email: admin@paws360.uwm.edu"
echo "  Password: admin123"
echo ""
echo -e "${BLUE}Useful Commands:${NC}"
echo "  Connect: docker exec -it $CONTAINER_NAME psql -U ${DB_USER} -d ${DB_NAME}"
echo "  Backup: docker exec $CONTAINER_NAME pg_dump -U ${DB_USER} -d ${DB_NAME} > backup.sql"
echo "  Monitor: docker exec $CONTAINER_NAME psql -U ${DB_USER} -d ${DB_NAME} -c 'SELECT * FROM paws360.dashboard_metrics;'"