openapi: 3.0.3
info:
  title: PAWS360 Authentication API
  description: Authentication and session management for PAWS360 platform
  version: 1.0.0
  contact:
    name: PAWS360 Development Team
    email: dev@university.edu

servers:
  - url: https://paws360.university.edu/api/v1
    description: Production server
  - url: https://paws360-staging.university.edu/api/v1
    description: Staging server

security:
  - BearerAuth: []
  - CookieAuth: []

paths:
  /auth/login:
    post:
      summary: Initiate SAML2 authentication
      description: Start SAML2 authentication flow with Azure AD
      operationId: initiateLogin
      tags:
        - Authentication
      security: []  # No auth required for login initiation
      responses:
        '302':
          description: Redirect to Azure AD SAML2 endpoint
          headers:
            Location:
              description: Azure AD SAML2 authentication URL
              schema:
                type: string
                format: uri
        '400':
          description: Invalid request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'

  /auth/saml/callback:
    post:
      summary: Handle SAML2 callback
      description: Process SAML2 assertion from Azure AD
      operationId: handleSamlCallback
      tags:
        - Authentication
      security: []  # No auth required for callback
      requestBody:
        required: true
        content:
          application/x-www-form-urlencoded:
            schema:
              type: object
              properties:
                SAMLResponse:
                  type: string
                  description: Base64 encoded SAML2 assertion
                RelayState:
                  type: string
                  description: Optional relay state parameter
              required:
                - SAMLResponse
      responses:
        '200':
          description: Authentication successful
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AuthenticationResponse'
        '401':
          description: Authentication failed
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'

  /auth/session:
    get:
      summary: Get current session information
      description: Retrieve current user session and profile data
      operationId: getCurrentSession
      tags:
        - Authentication
      responses:
        '200':
          description: Session information retrieved
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/SessionInfo'
        '401':
          description: Not authenticated
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'

  /auth/logout:
    post:
      summary: Logout current user
      description: End current session and optionally initiate SAML logout
      operationId: logout
      tags:
        - Authentication
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                saml_logout:
                  type: boolean
                  description: Whether to perform SAML logout with Azure AD
                  default: true
      responses:
        '200':
          description: Logout successful
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: "Logout successful"
                  saml_logout_url:
                    type: string
                    format: uri
                    description: SAML logout URL if saml_logout was requested
        '401':
          description: Not authenticated
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'

  /auth/refresh:
    post:
      summary: Refresh authentication token
      description: Extend current session or refresh JWT token
      operationId: refreshToken
      tags:
        - Authentication
      responses:
        '200':
          description: Token refreshed successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/TokenResponse'
        '401':
          description: Refresh failed - reauthentication required
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'

components:
  securitySchemes:
    BearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
    CookieAuth:
      type: apiKey
      in: cookie
      name: PAWS360_SESSION

  schemas:
    AuthenticationResponse:
      type: object
      required:
        - user
        - token
        - expires_at
      properties:
        user:
          $ref: '#/components/schemas/User'
        token:
          type: string
          description: JWT access token
          example: "eyJhbGciOiJIUzI1NiIs..."
        refresh_token:
          type: string
          description: JWT refresh token
        expires_at:
          type: string
          format: date-time
          description: Token expiration timestamp
        session_id:
          type: string
          description: Server-side session identifier

    SessionInfo:
      type: object
      required:
        - user
        - session_id
        - created_at
        - expires_at
      properties:
        user:
          $ref: '#/components/schemas/User'
        session_id:
          type: string
        created_at:
          type: string
          format: date-time
        last_accessed_at:
          type: string
          format: date-time
        expires_at:
          type: string
          format: date-time
        ip_address:
          type: string
        permissions:
          type: array
          items:
            type: string
          example: ["READ_STUDENT_DATA", "CREATE_ALERTS", "VIEW_ANALYTICS"]

    TokenResponse:
      type: object
      required:
        - token
        - expires_at
      properties:
        token:
          type: string
          description: New JWT access token
        expires_at:
          type: string
          format: date-time

    User:
      type: object
      required:
        - id
        - user_type
        - email
        - first_name
        - last_name
      properties:
        id:
          type: integer
          format: int64
        user_type:
          type: string
          enum: [STUDENT, STAFF]
        email:
          type: string
          format: email
        first_name:
          type: string
        last_name:
          type: string
        student_id:
          type: string
          description: Present for STUDENT user_type
        employee_id:
          type: string
          description: Present for STAFF user_type
        department:
          type: string
          description: Present for STAFF user_type
        role_type:
          type: string
          enum: [FACULTY, ADVISOR, ADMIN, SUPPORT]
          description: Present for STAFF user_type

    Error:
      type: object
      required:
        - error
        - message
      properties:
        error:
          type: string
          description: Error code
          example: "AUTHENTICATION_FAILED"
        message:
          type: string
          description: Human-readable error message
          example: "Invalid SAML assertion"
        details:
          type: object
          description: Additional error context
        timestamp:
          type: string
          format: date-time
        path:
          type: string
          description: Request path that generated the error