openapi: 3.0.3
info:
  title: PAWS360 Communication API
  description: Messaging, alerts, and communication channels
  version: 1.0.0
  contact:
    name: PAWS360 Development Team
    email: dev@university.edu

servers:
  - url: https://paws360.university.edu/api/v1
    description: Production server
  - url: https://paws360-staging.university.edu/api/v1
    description: Staging server

security:
  - BearerAuth: []
  - CookieAuth: []

paths:
  /alerts:
    get:
      summary: Get alerts for current user
      description: Retrieve alerts assigned to or created by current user
      operationId: getAlerts
      tags:
        - Alerts
      parameters:
        - name: status
          in: query
          schema:
            type: string
            enum: [OPEN, IN_PROGRESS, RESOLVED, DISMISSED]
          description: Filter by alert status
        - name: severity
          in: query
          schema:
            type: string
            enum: [LOW, MEDIUM, HIGH, CRITICAL]
          description: Filter by alert severity
        - name: alert_type
          in: query
          schema:
            type: string
            enum: [ACADEMIC, ATTENDANCE, FINANCIAL, PERSONAL, TECHNICAL]
          description: Filter by alert type
        - name: student_id
          in: query
          schema:
            type: string
          description: Filter by student (staff access required)
        - name: limit
          in: query
          schema:
            type: integer
            default: 50
            maximum: 100
          description: Maximum number of alerts to return
        - name: offset
          in: query
          schema:
            type: integer
            default: 0
          description: Number of alerts to skip
      responses:
        '200':
          description: Alerts retrieved successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AlertsList'

    post:
      summary: Create new alert
      description: Create alert for a student (staff access required)
      operationId: createAlert
      tags:
        - Alerts
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CreateAlertRequest'
      responses:
        '201':
          description: Alert created successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Alert'
        '400':
          description: Invalid request data
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        '403':
          description: Insufficient permissions
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'

  /alerts/{alertId}:
    get:
      summary: Get alert by ID
      description: Retrieve specific alert details
      operationId: getAlert
      tags:
        - Alerts
      parameters:
        - name: alertId
          in: path
          required: true
          schema:
            type: integer
            format: int64
      responses:
        '200':
          description: Alert retrieved successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Alert'
        '404':
          description: Alert not found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'

    put:
      summary: Update alert
      description: Update alert status, assignment, or resolution
      operationId: updateAlert
      tags:
        - Alerts
      parameters:
        - name: alertId
          in: path
          required: true
          schema:
            type: integer
            format: int64
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UpdateAlertRequest'
      responses:
        '200':
          description: Alert updated successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Alert'
        '400':
          description: Invalid request data
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        '404':
          description: Alert not found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'

  /messages:
    get:
      summary: Get messages for current user
      description: Retrieve messages sent to or from current user
      operationId: getMessages
      tags:
        - Messages
      parameters:
        - name: thread_id
          in: query
          schema:
            type: string
          description: Filter by message thread
        - name: status
          in: query
          schema:
            type: string
            enum: [SENT, DELIVERED, READ, FAILED]
          description: Filter by message status
        - name: limit
          in: query
          schema:
            type: integer
            default: 50
            maximum: 100
        - name: offset
          in: query
          schema:
            type: integer
            default: 0
      responses:
        '200':
          description: Messages retrieved successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/MessagesList'

    post:
      summary: Send message
      description: Send message to another user
      operationId: sendMessage
      tags:
        - Messages
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/SendMessageRequest'
      responses:
        '201':
          description: Message sent successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Message'
        '400':
          description: Invalid request data
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'

  /messages/{messageId}/read:
    put:
      summary: Mark message as read
      description: Mark specific message as read by current user
      operationId: markMessageRead
      tags:
        - Messages
      parameters:
        - name: messageId
          in: path
          required: true
          schema:
            type: integer
            format: int64
      responses:
        '200':
          description: Message marked as read
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: "Message marked as read"
                  read_at:
                    type: string
                    format: date-time

  /notifications:
    get:
      summary: Get notifications for current user
      description: Retrieve system notifications and alerts
      operationId: getNotifications
      tags:
        - Notifications
      parameters:
        - name: unread_only
          in: query
          schema:
            type: boolean
            default: false
          description: Return only unread notifications
        - name: limit
          in: query
          schema:
            type: integer
            default: 20
            maximum: 50
      responses:
        '200':
          description: Notifications retrieved successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/NotificationsList'

  /notifications/{notificationId}/read:
    put:
      summary: Mark notification as read
      description: Mark specific notification as read
      operationId: markNotificationRead
      tags:
        - Notifications
      parameters:
        - name: notificationId
          in: path
          required: true
          schema:
            type: integer
            format: int64
      responses:
        '200':
          description: Notification marked as read

components:
  securitySchemes:
    BearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
    CookieAuth:
      type: apiKey
      in: cookie
      name: PAWS360_SESSION

  schemas:
    Alert:
      type: object
      required:
        - id
        - student_id
        - created_by_id
        - alert_type
        - severity
        - title
        - description
        - status
        - created_at
      properties:
        id:
          type: integer
          format: int64
        student_id:
          type: integer
          format: int64
        student:
          $ref: '#/components/schemas/StudentSummary'
        created_by_id:
          type: integer
          format: int64
        created_by:
          $ref: '#/components/schemas/StaffSummary'
        alert_type:
          type: string
          enum: [ACADEMIC, ATTENDANCE, FINANCIAL, PERSONAL, TECHNICAL]
        severity:
          type: string
          enum: [LOW, MEDIUM, HIGH, CRITICAL]
        category:
          type: string
        title:
          type: string
        description:
          type: string
        recommended_actions:
          type: string
        status:
          type: string
          enum: [OPEN, IN_PROGRESS, RESOLVED, DISMISSED]
        assigned_to_id:
          type: integer
          format: int64
        assigned_to:
          $ref: '#/components/schemas/StaffSummary'
        resolution_notes:
          type: string
        resolved_at:
          type: string
          format: date-time
        follow_up_required:
          type: boolean
        follow_up_date:
          type: string
          format: date
        created_at:
          type: string
          format: date-time
        updated_at:
          type: string
          format: date-time

    CreateAlertRequest:
      type: object
      required:
        - student_id
        - alert_type
        - severity
        - title
        - description
      properties:
        student_id:
          type: string
          description: University student ID
        alert_type:
          type: string
          enum: [ACADEMIC, ATTENDANCE, FINANCIAL, PERSONAL, TECHNICAL]
        severity:
          type: string
          enum: [LOW, MEDIUM, HIGH, CRITICAL]
        category:
          type: string
        title:
          type: string
          maxLength: 200
        description:
          type: string
        recommended_actions:
          type: string
        assigned_to_id:
          type: integer
          format: int64
        follow_up_required:
          type: boolean
          default: false
        follow_up_date:
          type: string
          format: date

    UpdateAlertRequest:
      type: object
      properties:
        status:
          type: string
          enum: [OPEN, IN_PROGRESS, RESOLVED, DISMISSED]
        assigned_to_id:
          type: integer
          format: int64
        resolution_notes:
          type: string
        follow_up_required:
          type: boolean
        follow_up_date:
          type: string
          format: date

    AlertsList:
      type: object
      properties:
        alerts:
          type: array
          items:
            $ref: '#/components/schemas/Alert'
        total:
          type: integer
        offset:
          type: integer
        limit:
          type: integer

    Message:
      type: object
      required:
        - id
        - sender_id
        - recipient_id
        - body
        - created_at
      properties:
        id:
          type: integer
          format: int64
        sender_id:
          type: integer
          format: int64
        sender:
          $ref: '#/components/schemas/UserSummary'
        recipient_id:
          type: integer
          format: int64
        recipient:
          $ref: '#/components/schemas/UserSummary'
        communication_type:
          type: string
          enum: [MESSAGE, NOTIFICATION, ALERT, APPOINTMENT]
        subject:
          type: string
        body:
          type: string
        priority:
          type: string
          enum: [LOW, NORMAL, HIGH, URGENT]
        delivery_method:
          type: string
          enum: [IN_APP, EMAIL, SMS, PUSH]
        status:
          type: string
          enum: [SENT, DELIVERED, READ, FAILED]
        read_at:
          type: string
          format: date-time
        thread_id:
          type: string
        reference_type:
          type: string
          enum: [ALERT, ENROLLMENT, APPOINTMENT]
        reference_id:
          type: integer
          format: int64
        created_at:
          type: string
          format: date-time

    SendMessageRequest:
      type: object
      required:
        - recipient_id
        - body
      properties:
        recipient_id:
          type: integer
          format: int64
        subject:
          type: string
          maxLength: 200
        body:
          type: string
        priority:
          type: string
          enum: [LOW, NORMAL, HIGH, URGENT]
          default: NORMAL
        delivery_method:
          type: string
          enum: [IN_APP, EMAIL, SMS, PUSH]
          default: IN_APP
        thread_id:
          type: string
        reference_type:
          type: string
          enum: [ALERT, ENROLLMENT, APPOINTMENT]
        reference_id:
          type: integer
          format: int64

    MessagesList:
      type: object
      properties:
        messages:
          type: array
          items:
            $ref: '#/components/schemas/Message'
        total:
          type: integer
        offset:
          type: integer
        limit:
          type: integer
        unread_count:
          type: integer

    Notification:
      type: object
      properties:
        id:
          type: integer
          format: int64
        title:
          type: string
        message:
          type: string
        type:
          type: string
          enum: [INFO, WARNING, ERROR, SUCCESS]
        read_at:
          type: string
          format: date-time
        action_url:
          type: string
        created_at:
          type: string
          format: date-time

    NotificationsList:
      type: object
      properties:
        notifications:
          type: array
          items:
            $ref: '#/components/schemas/Notification'
        total:
          type: integer
        unread_count:
          type: integer

    StudentSummary:
      type: object
      properties:
        id:
          type: integer
          format: int64
        student_id:
          type: string
        first_name:
          type: string
        last_name:
          type: string
        email:
          type: string
        major:
          type: string
        classification:
          type: string

    StaffSummary:
      type: object
      properties:
        id:
          type: integer
          format: int64
        employee_id:
          type: string
        first_name:
          type: string
        last_name:
          type: string
        email:
          type: string
        job_title:
          type: string
        department:
          type: string

    UserSummary:
      type: object
      properties:
        id:
          type: integer
          format: int64
        first_name:
          type: string
        last_name:
          type: string
        email:
          type: string
        user_type:
          type: string
          enum: [STUDENT, STAFF]

    Error:
      type: object
      required:
        - error
        - message
      properties:
        error:
          type: string
        message:
          type: string
        details:
          type: object
        timestamp:
          type: string
          format: date-time
        path:
          type: string