export const graduationTerms = [
	"Spring 2025",
	"Fall 2025",
	"Winter 2025",
	"Spring 2026",
	"Fall 2026",
];

export const colleges = [
	"College of Engineering",
	"College of Business Administration",
	"College of Arts and Sciences",
	"College of Education",
	"College of Nursing and Health Sciences",
	"College of Fine Arts",
	"College of Computer Science and Technology",
	"College of Social Sciences",
	"College of Natural Sciences",
	"College of Communication and Media Studies",
];

export const majorsByCollege: Record<string, Record<string, string[]>> = {
	"College of Engineering": {
		"Bachelor of Science": [
			"Computer Science",
			"Mechanical Engineering",
			"Electrical Engineering",
			"Civil Engineering",
			"Chemical Engineering",
			"Aerospace Engineering",
			"Industrial Engineering",
			"Environmental Engineering",
			"Biomedical Engineering",
			"Computer Engineering",
			"Materials Science Engineering",
		],
		"Master of Science": [
			"Advanced Mechanical Systems",
			"Power Systems Engineering",
			"Structural Engineering",
			"Process Engineering",
			"Aeronautical Systems",
		],
		"Doctor of Philosophy": [
			"Engineering Science",
			"Advanced Materials",
			"Robotics and Automation",
		],
		"Professional Doctorate": ["Engineering Management"],
	},
	"College of Business Administration": {
		"Bachelor of Science": [
			"Accounting",
			"Finance",
			"Marketing",
			"Management",
			"Business Analytics",
			"International Business",
			"Supply Chain Management",
			"Entrepreneurship",
			"Human Resource Management",
			"Real Estate",
		],
		"Bachelor of Arts": ["Business Economics", "Organizational Leadership"],
		"Master of Business Administration": [
			"General MBA",
			"Executive MBA",
			"Healthcare Management",
			"Technology Management",
		],
		"Doctor of Philosophy": ["Business Administration", "Economics"],
	},
	"College of Arts and Sciences": {
		"Bachelor of Arts": [
			"English Literature",
			"History",
			"Philosophy",
			"Political Science",
			"Sociology",
			"Psychology",
			"Anthropology",
			"Economics",
			"Foreign Languages",
			"Art History",
		],
		"Bachelor of Science": [
			"Psychology",
			"Economics",
			"Geography",
			"Environmental Studies",
		],
		"Master of Arts": [
			"English Literature",
			"History",
			"Philosophy",
			"Political Science",
		],
		"Doctor of Philosophy": [
			"English",
			"History",
			"Political Science",
			"Psychology",
		],
	},
	"College of Education": {
		"Bachelor of Science": [
			"Elementary Education",
			"Secondary Education",
			"Special Education",
			"Early Childhood Education",
			"Physical Education",
			"Educational Technology",
			"Music Education",
			"Art Education",
			"Mathematics Education",
			"Science Education",
		],
		"Master of Education": [
			"Curriculum and Instruction",
			"Educational Leadership",
			"School Counseling",
			"Special Education",
		],
		"Doctor of Philosophy": ["Education", "Educational Psychology"],
		"Doctor of Education": ["Educational Leadership"],
	},
	"College of Nursing and Health Sciences": {
		"Bachelor of Science": [
			"Nursing",
			"Public Health",
			"Health Administration",
			"Nutrition Science",
			"Exercise Science",
			"Medical Laboratory Science",
			"Respiratory Therapy",
			"Radiologic Sciences",
			"Health Informatics",
			"Occupational Therapy",
		],
		"Master of Science": [
			"Nursing",
			"Public Health",
			"Health Administration",
			"Nurse Practitioner",
		],
		"Doctor of Nursing Practice": ["Advanced Practice Nursing"],
		"Doctor of Philosophy": ["Nursing Science", "Public Health"],
	},
	"College of Fine Arts": {
		"Bachelor of Arts": [
			"Studio Art",
			"Graphic Design",
			"Photography",
			"Art Education",
		],
		"Bachelor of Fine Arts": [
			"Painting",
			"Sculpture",
			"Ceramics",
			"Printmaking",
			"Digital Arts",
			"Film Production",
		],
		"Bachelor of Music": [
			"Music Performance",
			"Music Composition",
			"Music Theory",
			"Jazz Studies",
		],
		"Master of Fine Arts": [
			"Studio Art",
			"Graphic Design",
			"Creative Writing",
			"Film Production",
		],
	},
	"College of Computer Science and Technology": {
		"Bachelor of Science": [
			"Computer Science",
			"Software Engineering",
			"Information Technology",
			"Cybersecurity",
			"Data Science",
			"Artificial Intelligence",
			"Web Development",
			"Game Development",
			"Network Engineering",
			"Cloud Computing",
		],
		"Master of Science": [
			"Computer Science",
			"Software Engineering",
			"Cybersecurity",
			"Data Science",
			"Artificial Intelligence",
		],
		"Doctor of Philosophy": ["Computer Science", "Information Systems"],
		"Professional Doctorate": ["Technology Management"],
	},
	"College of Social Sciences": {
		"Bachelor of Arts": [
			"Sociology",
			"Social Work",
			"Criminal Justice",
			"Urban Studies",
			"Gender Studies",
			"International Relations",
			"Public Policy",
			"Human Services",
			"Gerontology",
			"Community Development",
		],
		"Bachelor of Science": ["Criminal Justice", "Public Administration"],
		"Master of Arts": ["Sociology", "Criminal Justice", "Public Policy"],
		"Master of Social Work": ["Clinical Social Work", "Community Practice"],
		"Doctor of Philosophy": ["Sociology", "Social Work"],
	},
	"College of Natural Sciences": {
		"Bachelor of Science": [
			"Biology",
			"Chemistry",
			"Physics",
			"Mathematics",
			"Geology",
			"Astronomy",
			"Environmental Science",
			"Biochemistry",
			"Marine Biology",
			"Microbiology",
		],
		"Master of Science": [
			"Biology",
			"Chemistry",
			"Physics",
			"Mathematics",
			"Environmental Science",
		],
		"Doctor of Philosophy": ["Biology", "Chemistry", "Physics", "Mathematics"],
	},
	"College of Communication and Media Studies": {
		"Bachelor of Arts": [
			"Journalism",
			"Public Relations",
			"Advertising",
			"Media Studies",
			"Broadcasting",
			"Digital Media",
			"Strategic Communication",
			"Multimedia Production",
			"Sports Communication",
			"Entertainment Media",
		],
		"Bachelor of Science": ["Media Production", "Digital Marketing"],
		"Master of Arts": ["Mass Communication", "Public Relations", "Journalism"],
		"Doctor of Philosophy": ["Communication", "Media Studies"],
	},
};

export const deliveryMethods = [
	{ value: "pickup", label: "Pick up in person" },
	{ value: "shipping", label: "Ship to my address" },
];
